### PR TITLE
Make Zookeeper nuget package

### PR DESCRIPTION
**Pull request by brugidou**
Hi,

I nugetized your zookeeper library to use with the nuget package manager. I didn't modify any code but i had to 
remove the lib/ folder and add a dependency on log4net.

The current version is published on nuget.org : https://nuget.org/packages/ZooKeeperNet

Let me know :)

Cheers,
Maxime

### CODE REVIEW

**Comment by CarlosTorrecillas** [comment]
Would it be possible for you to update the NuGet package with the latest code?

**Comment by brugidou** [comment]
@CarlosTorrecillas i don't use nor maintain this anymore, would you like to get ownership of this nuget package?

**Comment by CarlosTorrecillas** [comment]
Hi @brugidou, I don't use that anymore either.

Thanks!
Carlos.

**Comment by pengweiqhca** [comment]
@CarlosTorrecillas Can you update log4net to 1.2.13.0, publicKeyToken="669e0ddf0bb1aa2a". Or use common.logging?

**Comment by CarlosTorrecillas** [comment]
@pengweiqhca I don't have any ownership of that package as far as I know. Perhaps you should contact @brugidou for that.

**Comment by brugidou** [comment]
@pengweiqhca if you give me your nuget username I'll make you owner

**Comment by pengweiqhca** [comment]
@brugidou my github username

**Comment by mhorstma** [comment]
any chance that an update to the latest version of log4net (2.0.5) could be made, and a new nuget package of ZooKeeper.net published to nuget.org?  Looks like this has been an issue for a while without getting much traction.

**Comment by ewhauser** [comment]
@mhorstma: There is a fork of my repo that is where the nuget packages are published from

**Comment by mhorstma** [comment]
Thanks for the response.  Can you point out which package on nuget.org is being published from the fork?  I've been looking at this one:  https://www.nuget.org/packages/ZooKeeper.Net/, which is bound to the old log4net lib.  It would be great to get a drop of ZooKeeper.Net that uses the newest version of log4net.

**Comment by ewhauser** [comment]
Most of the relevant details are in this JIRA:

https://issues.apache.org/jira/browse/ZOOKEEPER-2209

**Comment by brugidou** [comment]
I'm closing this, please use the official package at https://www.nuget.org/packages/ZooKeeper.Net/
I will unlist the zookeepernet package soon.

**Pull request closed without merging**
