### PR TITLE
fixes for dotnet client

### PR DESCRIPTION
**Pull request by koltsov-ps**

### CODE REVIEW

**Comment by pierre-dejoue** [comment]
+1. We also ran into the [reconnection bug](https://github.com/koltsov-ps/zookeeper/commit/026265e43936a12ece56e1aa3d6d652922601220), this one should really be merged.

**Comment by ewhauser** [comment]
There are conflicts in the pull request so it can't be merged.  Can you rebase your branch against trunk and I'll merge it?

**Comment by pierre-dejoue** [comment]
Hi Eric,

I created https://github.com/ewhauser/zookeeper/pull/24 which is a rebase of this pull request.

Thanks!

**Comment by ewhauser** [comment]
Thanks, closing this one and merging it.

**Pull request closed without merging**
